driver:
  name: vagrant
  boot_timeout: 1200
  gui: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2019
    driver_config:
      box: tas50/windows_2019
    driver:
      vm_hostname: windows
      network:
        - ["private_network", {ip: "192.168.33.38"}]
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[Windows_memberserver_2019_Security_baseline::default]
    verifier:
      inspec_tests:
        - test/smoke/default/
    attributes: